export const GROUP_ASSIGNMENT_REQUEST_DATAS="GROUP_ASSIGNMENT_REQUEST_DATAS"

export const GROUP_ASSIGNMENT_RECEIVE_DATAS="GROUP_ASSIGNMENT_RECEIVE_DATAS"

export const GROUP_ASSIGNMENT_RESET_STATE="GROUP_ASSIGNMENT_RESET_STATE"

export const GROUP_ASSIGNMENT_ASSIGN_SUCESS="GROUP_ASSIGNMENT_ASSIGN_SUCESS"

export const GROUP_ASSIGNMENT_UN_ASSIGN_SUCESS="GROUP_ASSIGNMENT_UN_ASSIGN_SUCESS"


export const KEY_GROUP_ASSIGNMENT_PROJECT_ID = 'project_id';
export const KEY_GROUP_ASSIGNMENT_USERNAME = 'username';
export const KEY_GROUP_ASSIGNMENT_GROUP = 'group';
export const KEY_GROUP_ASSIGNMENT_DISPLAYNAME = 'display_name';
export const KEY_GROUP_ASSIGNMENT_ROLES = 'roles';

export const KEY_GROUP_ASSIGNMENT_PARENT_NAME = 'assign_parent_name';


export const TITLE_GROUP_ASSIGNMENT_USERNAME = 'Username';
export const TITLE_GROUP_ASSIGNMENT_GROUP = 'Group Users';
export const TITLE_GROUP_ASSIGNMENT_DISPLAYNAME = 'Display Name';
export const TITLE_GROUP_ASSIGNMENT_ROLES = 'Roles';
