export const TRANFORM_CONFIGURATION_GET_DATA = '$DGS/TRANFORM_CONFIGURATION_GET_DATA';
export const TRANFORM_CONFIGURATION_UNMOUNT = '$DGS/TRANFORM_CONFIGURATION_UNMOUNT';
export const PENDING = '$DGS/TRANFORM_CONFIGURATION_PENDING';
export const ERROR = '$DGS/TRANFORM_CONFIGURATION_ERROR';
export const ADD_CONFIG = '$DGS/TRANFORM_CONFIGURATION_ADD_CONFIG';
export const TRANFORM_CONFIGURATION_DELETE_DATA = '$DGS/TRANFORM_CONFIGURATION_DELETE_DATA';
export const TRANFORM_CONFIGURATION_UPDATE_DATA  = '$DGS/TRANFORM_CONFIGURATION_UPDATE_DATA ';

