export const SEND_HTTP_REQUEST = 'SEND_HTTP_REQUEST';
export const RECEIVE_HTTP_RESPONSE = 'RECEIVE_HTTP_RESPONSE';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';
export const OPEN_SNACKBAR = 'OPEN_SNACKBAR';
