export declare const aliases: {
    'windows': number;
    '⇧': number;
    '⌥': number;
    '⌃': number;
    '⌘': number;
    'ctl': number;
    'control': number;
    'option': number;
    'pause': number;
    'break': number;
    'caps': number;
    'return': number;
    'escape': number;
    'spc': number;
    'spacebar': number;
    'pgup': number;
    'pgdn': number;
    'ins': number;
    'del': number;
    'cmd': number;
};
export declare const codes: {
    'backspace': number;
    'tab': number;
    'enter': number;
    'shift': number;
    'ctrl': number;
    'alt': number;
    'pause/break': number;
    'caps lock': number;
    'esc': number;
    'space': number;
    'page up': number;
    'page down': number;
    'end': number;
    'home': number;
    'left': number;
    'up': number;
    'right': number;
    'down': number;
    'insert': number;
    'delete': number;
    'command': number;
    'left command': number;
    'right command': number;
    'numpad *': number;
    'numpad +': number;
    'numpad -': number;
    'numpad .': number;
    'numpad /': number;
    'num lock': number;
    'scroll lock': number;
    'my computer': number;
    'my calculator': number;
    ';': number;
    '=': number;
    ',': number;
    '-': number;
    '.': number;
    '/': number;
    '`': number;
    '[': number;
    '\\': number;
    ']': number;
    "'": number;
};
export declare const names: {};
