/**
 * AJAX ACTION DEFINITION
 */

export const ERROR_ITEM_SHOW_DIALOG = 'ERROR_ITEM_SHOW_DIALOG';
export const ERROR_ITEM_HIDE_DIALOG = 'ERROR_ITEM_HIDE_DIALOG';


/**
 * PARAMETER ITEM
 */
export const KEY_ERROR_NAME = 'name';
export const KEY_ERROR_CODE = 'code';
export const KEY_ERROR_DESCRIPTION = 'description';
export const KEY_ERROR_ID = 'id';

/**
 * ERROR LIST
 */
export const ERROR_LIST_REQUEST = 'ERROR_LIST_REQUEST';
export const ERROR_LIST_RESET_DATA = 'ERROR_LIST_RESET_DATA';
export const ERROR_LIST_RESPONSE = 'ERROR_LIST_RESPONSE';

/**
 * ERROR ITEM ACTION
 */
export const ERROR_ITEM_REQUEST = 'ERROR_ITEM_REQUEST';
export const ERROR_ITEM_RESPONSE = 'ERROR_ITEM_RESPONSE';
export const ERROR_ITEM_ERROR_DATA = 'ERROR_ITEM_ERROR_DATA';

export const ERROR_ITEM_CREATE_EMPTY_DATA = 'ERROR_ITEM_CREATE_EMPTY_DATA';

export const ERROR_ITEM_MODIFY_DATA = 'ERROR_ITEM_MODIFY_DATA';
export const ERROR_ITEM_VALIDATE = 'ERROR_ITEM_VALIDATE';

export const ERROR_ITEM_RESET = 'ERROR_ITEM_RESET';