export const WORKFLOW_ITEM_CONFIG_SHOW = 'WORKFLOW_ITEM_CONFIG_SHOW';
export const WORKFLOW_ITEM_CONFIG_HIDE = 'WORKFLOW_ITEM_CONFIG_HIDE';
export const WORKFLOW_ITEM_CONFIG_SET_SECTIONS = 'WORKFLOW_ITEM_CONFIG_SET_SECTIONS';
export const WORKFLOW_ITEM_CONFIG_SET_SERVICES = 'WORKFLOW_ITEM_CONFIG_SET_SERVICES';
export const WORKFLOW_ITEM_CONFIG_SET_LAYOUTS= 'WORKFLOW_ITEM_CONFIG_SET_LAYOUTS';

export const WORKFLOW_ITEM_HISTORY_SHOW = 'WORKFLOW_ITEM_HISTORY_SHOW';
export const WORKFLOW_ITEM_HISTORY_HIDE = 'WORKFLOW_ITEM_HISTORY_HIDE';
export const WORKFLOW_ITEM_HISTORY_SET_LIST = 'WORKFLOW_ITEM_HISTORY_SET_LIST';

export const WORKFLOW_ITEM_MONITOR_VALID = 'WORKFLOW_ITEM_MONITOR_VALID';
export const WORKFLOW_ITEM_MONITOR_CHANGE_SOURCE_ACTIVITY = 'WORKFLOW_ITEM_MONITOR_CHANGE_SOURCE_ACTIVITY';
export const WORKFLOW_ITEM_MONITOR_CHANGE_TARGET_ACTIVITY = 'WORKFLOW_ITEM_MONITOR_CHANGE_TARGET_ACTIVITY';
export const WORKFLOW_ITEM_MONITOR_EXCHANGE = 'WORKFLOW_ITEM_MONITOR_EXCHANGE';
export const WORKFLOW_ITEM_MONITOR_SHOW_VIEW_INSTANCES = 'WORKFLOW_ITEM_MONITOR_SHOW_VIEW_INSTANCES';
export const WORKFLOW_ITEM_MONITOR_HIDE_VIEW_INSTANCES = 'WORKFLOW_ITEM_MONITOR_HIDE_VIEW_INSTANCES';
export const WORKFLOW_ITEM_MONITOR_SHOW_VIEW_EXCHANGE = 'WORKFLOW_ITEM_MONITOR_SHOW_VIEW_EXCHANGE';
export const WORKFLOW_ITEM_MONITOR_HIDE_VIEW_EXCHANGE = 'WORKFLOW_ITEM_MONITOR_HIDE_VIEW_EXCHANGE';

export const WORKFLOW_ITEM_SET_CANVAS = 'WORKFLOW_ITEM_SET_CANVAS';
export const WORKFLOW_ITEM_CHANGE_VERSION = 'WORKFLOW_ITEM_CHANGE_VERSION';
export const WORKFLOW_ITEM_GETTING = 'WORKFLOW_ITEM_GETTING';
export const WORKFLOW_ITEM_GET_DONE = 'WORKFLOW_ITEM_GET_DONE';
export const WORKFLOW_ITEM_DEPLOYED = 'WORKFLOW_ITEM_DEPLOYED';
export const WORKFLOW_ITEM_CREATE = 'WORKFLOW_ITEM_CREATE';
export const WORKFLOW_ITEM_CHANGE_TYPE = 'WORKFLOW_ITEM_CHANGE_TYPE';
export const WORKFLOW_ITEM_CHANGE_LAYOUT = 'WORKFLOW_ITEM_CHANGE_LAYOUT';
export const WORKFLOW_ITEM_HIDE_CONFIRM = 'WORKFLOW_ITEM_HIDE_CONFIRM';
export const WORKFLOW_ITEM_SHOW_CONFIRM = 'WORKFLOW_ITEM_SHOW_CONFIRM';
export const WORKFLOW_ITEM_SET_DATA = 'WORKFLOW_ITEM_SET_DATA';
export const WORKFLOW_ITEM_ERROR = 'WORKFLOW_ITEM_ERROR';
export const WORKFLOW_ITEM_VALID = 'WORKFLOW_ITEM_VALID';
export const WORKFLOW_ITEM_RESET = 'WORKFLOW_ITEM_RESET';
export const WORKFLOW_ITEM_SET_INSTANCES = 'WORKFLOW_ITEM_SET_INSTANCES';
export const WORKFLOW_ITEM_EXPAND = 'WORKFLOW_ITEM_EXPAND';

export const WORKFLOW_LIST_GETTING = 'WORKFLOW_LIST_GETTING';
export const WORKFLOW_LIST_GET_DONE = 'WORKFLOW_LIST_GET_DONE';
export const WORKFLOW_LIST_RESET = 'WORKFLOW_LIST_RESET';

export const WORKFLOW_MIGRATION_MIGRATION_DONE = 'WORKFLOW_MIGRATION_MIGRATION_DONE';
export const WORKFLOW_MIGRATION_ERROR = 'WORKFLOW_MIGRATION_ERROR';
export const WORKFLOW_MIGRATION_CHANGE_TARGET_ACTIVITY = 'WORKFLOW_MIGRATION_CHANGE_TARGET_ACTIVITY';
export const WORKFLOW_MIGRATION_UNSELECT_DATA_SOURCE = 'WORKFLOW_MIGRATION_UNSELECT_DATA_SOURCE';
export const WORKFLOW_MIGRATION_SELECT_DATA_SOURCE = 'WORKFLOW_MIGRATION_SELECT_DATA_SOURCE';
export const WORKFLOW_MIGRATION_SELECT_DATA_TARGET = 'WORKFLOW_MIGRATION_SELECT_DATA_TARGET';
export const WORKFLOW_MIGRATION_GETTING = 'WORKFLOW_MIGRATION_GETTING';
export const WORKFLOW_MIGRATION_GET_DONE = 'WORKFLOW_MIGRATION_GET_DONE';