/**
 * AJAX ACTION DEFINITION
 */

export const SERVICE_ITEM_SET_DIALOG = 'SERVICE_ITEM_SET_DIALOG';

/**
 * PARAMETER ITEM
 */

export const KEY_SERVICE_NAME = 'service_name';
export const KEY_SERVICE_JAVA_CLASS = 'java_class';
export const KEY_SERVICE_PARAMETERS = 'parameters';
export const KEY_SERVICE_LABEL_PARAMETERS = 'label_parameters';

export const SUBKEY_SERVICE_PARAMETER_NAME = 'name';
export const SUBKEY_SERVICE_PARAMETER_TYPE = 'type';
export const SUBKEY_SERVICE_PARAMETER_VALUE = 'value';
export const SUBKEY_SERVICE_PARAMETER_INVISIBLE = 'invisible';

/**
 * SERVICE LIST
 */
export const SERVICE_LIST_REQUEST = 'SERVICE_LIST_REQUEST';
export const SERVICE_LIST_RESET_DATA = 'SERVICE_LIST_RESET_DATA';
export const SERVICE_LIST_RESPONSE = 'SERVICE_LIST_RESPONSE';

/**
 * SERVICE ITEM ACTION
 */
export const SERVICE_ITEM_REQUEST = 'SERVICE_ITEM_REQUEST';
export const SERVICE_ITEM_RESPONSE = 'SERVICE_ITEM_RESPONSE';
export const SERVICE_ITEM_ERROR_DATA = 'SERVICE_ITEM_ERROR_DATA';

export const SERVICE_ITEM_CREATE_EMPTY_DATA = 'SERVICE_ITEM_CREATE_EMPTY_DATA';

export const SERVICE_ITEM_SHOW_DIALOG = 'SERVICE_ITEM_SHOW_DIALOG';
export const SERVICE_ITEM_HIDE_DIALOG = 'SERVICE_ITEM_HIDE_DIALOG';

export const SERVICE_ITEM_MODIFY_DATA = 'SERVICE_ITEM_MODIFY_DATA';
export const SERVICE_ITEM_SERVICE = 'SERVICE_ITEM_SERVICE';

export const SERVICE_ITEM_RESET = 'SERVICE_ITEM_RESET';
