export const LAYOUT_SIDEBAR_SELECT = 'LAYOUT_SIDEBAR_SELECT';

export const LAYOUT_ACTIVE_TAB = 'LAYOUT_ACTIVE_TAB';

export const MUI_THEME_STYLE_CYAN = 'MUI_THEME_STYLE_CYAN';
export const MUI_THEME_STYLE_BLUE = 'MUI_THEME_STYLE_BLUE';
export const MUI_THEME_STYLE_PURPLE = 'MUI_THEME_STYLE_PURPLE';
export const MUI_THEME_STYLE_GREY = 'MUI_THEME_STYLE_GREY';
