export const DETAIL_SOUCRES_LIST_LAYOUTS_REQUEST = "DETAIL_SOUCRES_LIST_LAYOUTS_REQUEST";

export const DETAIL_SOUCRES_LIST_LAYOUTS_RECEIVE = "DETAIL_SOUCRES_LIST_LAYOUTS_RECEIVE";

export const PROJECT_LAYOUT_ATTRIBUTE_INCLUDES = "id,name";

export const DETAIL_SOUCRES_RESET_STATE = "DETAIL_SOUCRES_RESET_STATE";