/**
 * PARAMETER ITEM
 */

export const KEY_EXPORT_CONFIGURATION_NAME = 'name';
export const KEY_EXPORT_CONFIGURATION_FIELD_SRC = 'fields_project';
export const KEY_EXPORT_CONFIGURATION_FIELD_EXPORT = 'fields_project';
export const KEY_EXPORT_CONFIGURATION_FIELD_EXPORT_SELECTED = 'name';

export const PARAMETER_FORMAT_TYPE_DB3 = 'DB3';
export const PARAMETER_FORMAT_TYPE_CSV = 'CSV';
export const PARAMETER_FORMAT_TYPE_XLS = 'XLS';
export const PARAMETER_FORMAT_TYPE_TXT = 'TXT';
export const PARAMETER_FORMAT_TYPE_XML = 'XML';

/**
 * EXPORT_CONFIGURATION LIST
 */
export const EXPORT_CONFIGURATION_LIST_REQUEST =
  'EXPORT_CONFIGURATION_LIST_REQUEST';
export const EXPORT_CONFIGURATION_LIST_RESET_DATA =
  'EXPORT_CONFIGURATION_LIST_RESET_DATA';
export const EXPORT_CONFIGURATION_LIST_RECEIVE_DATAS =
  'EXPORT_CONFIGURATION_LIST_RECEIVE_DATAS';

/**
 * EXPORT_CONFIGURATION ITEM ACTION
 */
export const EXPORT_CONFIGURATION_ITEM_RECEIVE_DATA =
  'EXPORT_CONFIGURATION_ITEM_RECEIVE_DATA';
export const EXPORT_CONFIGURATION_ITEM_INSERT_DATA =
  'EXPORT_CONFIGURATION_ITEM_INSERT_DATA';
export const EXPORT_CONFIGURATION_ITEM_MODIFY_DATA =
  'EXPORT_CONFIGURATION_ITEM_MODIFY_DATA';
export const EXPORT_CONFIGURATION_ITEM_RESET_DATA =
  'EXPORT_CONFIGURATION_ITEM_RESET_DATA';
/**
 * FIELD MAPPING
 */
export const EXPORT_CONFIGURATION_UPDATE_FIELD_EXPORT =
  'EXPORT_CONFIGURATION_UPDATE_FIELD_EXPORT';
export const EXPORT_CONFIGURATION_UPDATE_FIELD_TYPE_ROOT_CONFIG =
  'EXPORT_CONFIGURATION_UPDATE_FIELD_TYPE_ROOT_CONFIG';
  export const EXPORT_CONFIGURATION_ADD_FIELD_ROOT_CONFIG =
  'EXPORT_CONFIGURATION_ADD_FIELD_ROOT_CONFIG';
  export const EXPORT_CONFIGURATION_EDIT_FIELD_ROOT_CONFIG =
  'EXPORT_CONFIGURATION_EDIT_FIELD_ROOT_CONFIG';
  
/**
 * SET_DIALOG
 */
export const SET_DIALOG = 'SET_DIALOG';
export const RESET_DIALOG = 'RESET_DIALOG';
/**
 * type export 
 */
