export const EXPORT_CONFIGURATION_GET_DATA = '$DGS/EXPORT_CONFIGURATION_GET_DATA';
export const EXPORT_CONFIGURATION_UNMOUNT = '$DGS/EXPORT_CONFIGURATION_UNMOUNT';
export const SET_IS_OPEN_ADD_DIALOG = '$DGS/EXPORT_CONFIGURATION_SET_IS_OPEN_ADD_DIALOG';
export const SET_IS_OPEN_EDIT_DIALOG = '$DGS/EXPORT_CONFIGURATION_SET_IS_OPEN_EDIT_DIALOG';
export const SET_IS_OPEN_DEL_DIALOG = '$DGS/EXPORT_CONFIGURATION_SET_IS_OPEN_DEL_DIALOG';
export const SET_IS_CLOSE_DIALOG = '$DGS/EXPORT_CONFIGURATION_SET_IS_CLOSE_DIALOG';