import { NAMESPACE_MODULE } from '../constant';
export const LAYOUT_FUNCTION = `${NAMESPACE_MODULE}_LAYOUT`

export const FETCH = `${LAYOUT_FUNCTION}_FETCH`;
export const FETCHING = `${LAYOUT_FUNCTION}_FETCHING`;
export const RECEIVE = `${LAYOUT_FUNCTION}_RECEIVE`;
export const DID_INVALIDATE = `${LAYOUT_FUNCTION}_DID_INVALIDATE`;
export const RESET = `${LAYOUT_FUNCTION}_RESET`;

export const SAVING = `${LAYOUT_FUNCTION}_SAVING`;
export const SAVE_LAYOUT_FAILED = `${LAYOUT_FUNCTION}_SAVE_LAYOUT_FAILED`;
export const CHANGE_NAME = `${LAYOUT_FUNCTION}_CHANGE_NAME`;
export const CHANGE_PROP = `${LAYOUT_FUNCTION}_CHANGE_PROP`;
export const REQUIRED_NAME = `${LAYOUT_FUNCTION}_REQUIRED_NAME`;

export const SAVE_LAYOUT_SUCCESS = `${LAYOUT_FUNCTION}_SAVE_LAYOUT_SUCCESS`;
export const CHANGE_HOT_KEY = `${LAYOUT_FUNCTION}_CHANGE_HOT_KEY`;
export const CHANGE_NON_CAPUTE = `${LAYOUT_FUNCTION}_CHANGE_NON_CAPUTE`;

export default {
    CHANGE_NON_CAPUTE,
    CHANGE_HOT_KEY,
    RESET,
    FETCH,
    FETCHING,
    RECEIVE,
    DID_INVALIDATE,
    CHANGE_NAME,
    REQUIRED_NAME,
    SAVING,
    SAVE_LAYOUT_FAILED,
    SAVE_LAYOUT_SUCCESS,
    CHANGE_PROP,
}