import { NAMESPACE_MODULE } from '../constant';
const SECIONS_FUNCION = `${NAMESPACE_MODULE}_SECTIONS`;


export const FETCHING = `${SECIONS_FUNCION}_FETCHING`;
export const RECEIVE = `${SECIONS_FUNCION}_RECEIVE`;
export const DID_INVALIDATION = `${SECIONS_FUNCION}_DID_INVALIDATION`;


export const ADD = `${SECIONS_FUNCION}_ADD`;
export const RESET = `${SECIONS_FUNCION}_RESET`;
export const CHOOSE = `${SECIONS_FUNCION}_CHOOSE`;
export const CHANGE_NAME = `${SECIONS_FUNCION}_CHANGE_NAME`;
export const CHANGE_POSITION = `${SECIONS_FUNCION}_CHANGE_POSITION`;
export const DELETE_SECTION = `${SECIONS_FUNCION}_DELETE_SECTION`;


export const ADD_FIELD = `${SECIONS_FUNCION}_ADD_FIELD`;
export const SORT_FIELDS = `${SECIONS_FUNCION}_SORT_FIELDS`;
export const CHANGE_FIELD = `${SECIONS_FUNCION}_CHANGE_FIELD`;
export const DELETE_FIELD = `${SECIONS_FUNCION}_DELETE_FIELD`;
export const CHANGE_POSITION_FIELD = `${SECIONS_FUNCION}_CHANGE_POSITION_FIELD`;
export const CHANGE_SETTING_FIELD = `${SECIONS_FUNCION}_CHANGE_SETTING_FIELD`;

export const CHOOSE_OPTION = `${SECIONS_FUNCION}_CHOOSE_OPTION`;
export const DELETE_POSITION_OPTION = `${SECIONS_FUNCION}_DELETE_POSITION_OPTION`;
export const CHANGE_POSITION_OPTION = `${SECIONS_FUNCION}_CHANGE_POSITION_OPTION`;


export const CHOOSE_FIELD = `${SECIONS_FUNCION}_CHOOSE_FIELD`;


export const OPEN_SETTING = `${SECIONS_FUNCION}_OPEN_SETTING`;
export const CLOSE_SETTING = `${SECIONS_FUNCION}_CLOSE_SETTING`;
export const CHANGE_SETTING = `${SECIONS_FUNCION}_CHANGE_SETTING`;

export const UPDATE_ID_FOR_ADD = `${SECIONS_FUNCION}_UPDATE_ID_FOR_ADD`;


export const RUNING_TEST = `${SECIONS_FUNCION}_RUNING_TEST`;
export const RUN_TEST_FAILED = `${SECIONS_FUNCION}_RUN_TEST_FAILED`;
export const RECEIVE_RUN_TEST = `${SECIONS_FUNCION}_RECEIVE_RUN_TEST`;
export const RESET_RUN_TEST_OMR = `${SECIONS_FUNCION}_RESET_RUN_TEST_OMR`;
export const SORT_SECTION = `${SECIONS_FUNCION}_SORT_SECTION`;
export default {
    SORT_SECTION,
    RUNING_TEST,
    RUN_TEST_FAILED,
    RECEIVE_RUN_TEST,
    RESET_RUN_TEST_OMR,
    OPEN_SETTING,
    CLOSE_SETTING,
    CHANGE_SETTING,
    FETCHING,
    DID_INVALIDATION,
    RECEIVE,
    CHOOSE_FIELD,
    UPDATE_ID_FOR_ADD,
    CHOOSE_OPTION,
    CHANGE_POSITION_OPTION,
    DELETE_POSITION_OPTION,
    ADD,
    RESET,
    CHOOSE,
    CHANGE_NAME,
    CHANGE_POSITION,
    ADD_FIELD,
    CHANGE_FIELD,
    SORT_FIELDS,
    DELETE_FIELD,
    DELETE_SECTION,
    CHANGE_POSITION_FIELD,
    CHANGE_SETTING_FIELD,

};
