export const QC_SAMPLING_UPDATE_SAMPLING_CONDITIONS =
  'QC_SAMPLING_UPDATE_SAMPLING_CONDITIONS';
export const QC_SAMPLING_RESET_STATE = 'QC_SAMPLING_RESET_STATE';

export const QC_SAMPLING_SEND_REQUEST_CALCULATE =
  'QC_SAMPLING_SEND_REQUEST_CALCULATE';
export const QC_SAMPLING_RECIEVE_RESULT_CALCULATE =
  'QC_SAMPLING_RECIEVE_RESULT_CALCULATE';

export const QC_SAMPLING_UPDATE_BIG_MENUS = 'QC_SAMPLING_UPDATE_BIG_MENUS';

export const QC_SAMPLING_SEND_REQUEST_SAMPLE =
  'QC_SAMPLING_SEND_REQUEST_SAMPLE';

/**
 * LENGTH
 */
export const MAX_LENGTH_OF_DATAS = 100;
export const LENGTH_CALL_API = 10;
export const TIME_OUT_FETCH_API = 1000;

/**
 * CONDITION ATTR
 */
export const ATTR_BATCH_REQUEST_DATAS = 'ATTR_BATCH_REQUEST_DATAS';
export const ATTR_BATCH_RECIEVE_DATAS = 'ATTR_BATCH_RECIEVE_DATAS';
export const ATTR_BATCH_SELECT_DATAS = 'ATTR_BATCH_SELECT_DATAS';
export const ATTR_BATCH_RESET_DATAS = 'ATTR_BATCH_RESET_DATAS';

export const ATTR_SECTION_REQUEST_DATAS = 'ATTR_SECTION_REQUEST_DATAS';
export const ATTR_SECTION_RECIEVE_DATAS = 'ATTR_SECTION_RECIEVE_DATAS';
export const ATTR_SECTION_SELECT_DATAS = 'ATTR_SECTION_SELECT_DATAS';
export const ATTR_SECTION_RESET_DATAS = 'ATTR_SECTION_RESET_DATAS';

export const ATTR_LAYOUT_REQUEST_DATAS = 'ATTR_LAYOUT_REQUEST_DATAS';
export const ATTR_LAYOUT_RECIEVE_DATAS = 'ATTR_LAYOUT_RECIEVE_DATAS';
export const ATTR_LAYOUT_SELECT_DATAS = 'ATTR_LAYOUT_SELECT_DATAS';
export const ATTR_LAYOUT_RESET_DATAS = 'ATTR_LAYOUT_RESET_DATAS';

export const ATTR_USER_REQUEST_DATAS = 'ATTR_USER_REQUEST_DATAS';
export const ATTR_USER_RECIEVE_DATAS = 'ATTR_USER_RECIEVE_DATAS';
export const ATTR_USER_SELECT_DATAS = 'ATTR_USER_SELECT_DATAS';
export const ATTR_USER_RESET_DATAS = 'ATTR_USER_RESET_DATAS';

export const ATTR_FIELD_REQUEST_DATAS = 'ATTR_FIELD_REQUEST_DATAS';
export const ATTR_FIELD_RECIEVE_DATAS = 'ATTR_FIELD_RECIEVE_DATAS';
export const ATTR_FIELD_SELECT_DATAS = 'ATTR_FIELD_SELECT_DATAS';
export const ATTR_FIELD_RESET_DATAS = 'ATTR_FIELD_RESET_DATAS';
export const ATTR_CONDITION_SEND_REQUEST = 'ATTR_CONDITION_SEND_REQUEST';
export const ATTR_CONDITION_RECIEVE_RESULT = 'ATTR_CONDITION_RECIEVE_RESULT';

/**
 * PROPERTIES
 */

export const QC_CONDITION_KEY_PROJECT_ID = 'project_id';

export const QC_CONDITION_KEY_BATCH = 'batch';
export const QC_CONDITION_KEY_SECTION = 'section';
export const QC_CONDITION_KEY_LAYOUT = 'layout';
export const QC_CONDITION_KEY_KEYER = 'keyer';
export const QC_CONDITION_KEY_QC_FIELDS = 'fields';
export const QC_CONDITION_KEY_APPLY_AQL_USER = 'apply_aql_user';

export const QC_CONDITION_KEY_INSPECTION_LEVEL = 'inspection';
export const QC_CONDITION_KEY_BATCH_NAME = 'batch_name';
/**
 * INSPECTION LEVEL
 */
export const INSPECTION_LEVEL_IMPORTANT_I = 'Important I';
export const INSPECTION_LEVEL_IMPORTANT_II = 'Important II';
export const INSPECTION_LEVEL_NORMAL_I = 'Normal I';
export const INSPECTION_LEVEL_NORMAL_II = 'Normal II';
export const INSPECTION_LEVEL_STABLE_I = 'Stable I';
export const INSPECTION_LEVEL_STABLE_II = 'Stable II';
