
export const RESET = '$DGS/GENERAL_CONFIGURATION_RESET';
export const PENDING = '$DGS/GENERAL_CONFIGURATION_PENDING';
export const ERROR = '$DGS/GENERAL_CONFIGURATION_ERROR';
export const SUCCESS = '$DGS/GENERAL_CONFIGURATION_SUCCESS';
export const GENERAL_CONFIGURATION_GET_DATA = '$DGS/GENERAL_CONFIGURATION_GET_DATA';
export const GENERAL_CONFIGURATION_GET_DATA_ERROR = '$DGS/GENERAL_CONFIGURATION_GET_DATA_ERROR';
export const GENERAL_CONFIGURATION_CLICK_ITEM = '$DGS/GENERAL_CONFIGURATION_CLICK_ITEM';
export const GENERAL_CONFIGURATION_MONDIFY_DATA = '$DGS/GENERAL_CONFIGURATION_MONDIFY_DATA';
export const GENERAL_CONFIGURATION_UNMOUNT = '$DGS/GENERAL_CONFIGURATION_UNMOUNT';
export const GENERAL_CONFIGURATION_GET_DATA_EXPORT_FORMAT = '$DGS/GENERAL_CONFIGURATION_GET_DATA_EXPORT_FORMAT';
export const GENERAL_CONFIGURATION_CRUD_ITEM_SUCCESS = '$DGS/GENERAL_CONFIGURATION_CRUD_ITEM_SUCCESS';
export const GENERAL_CONFIGURATION_ADD_NEW_ITEM = '$DGS/GENERAL_CONFIGURATION_ADD_NEW_ITEM';
export const GENERAL_CONFIGURATION_UPDATE_ITEM = '$DGS/GENERAL_CONFIGURATION_UPDATE_ITEM';

export const GENERAL_CONFIGURATION_GET_DATA_GENERAL_CONFIGURATION = '$DGS/GENERAL_CONFIGURATION_GET_DATA_GENERAL_CONFIGURATION';