/**user AD */
export const USER_AD_LIST_REQUEST = 'USER_AD_LIST_REQUEST';
export const USER_AD_LIST_RECEIVE = 'USER_AD_LIST_RECEIVE';
export const USER_AD_LIST_RESET_STATE = 'USER_AD_LIST_RESET_STATE';