export declare const REGEX_EMPTY: RegExp;
export declare const REGEX_NUMBER: RegExp;
export declare const REGEX_PHONE: RegExp;
export declare const REGEX_EMAIL: RegExp;
export declare const REGEX_CHARACTERS: RegExp;
export declare const REGEX_PASSWORD: RegExp;
export declare const REGEX_CHARACTERS_UTF8: RegExp;
export declare const KEY_FIELD_TYPE = "type";
export declare const KEY_FIELD_TYPE_TEXT = "text";
export declare const KEY_FIELD_TYPE_NUMBER_INT = "number_int";
export declare const KEY_FIELD_TYPE_NUMBER_FLOAT = "number_float";
export declare const KEY_FIELD_TYPE_PASSWORD = "password";
export declare const KEY_FIELD_TYPE_DATE = "date";
export declare const KEY_FIELD_TYPE_BOOLEAN = "boolean";
export declare const KEY_FIELD_TYPE_CRON_TRIGGER = "cron_trigger";
export declare const KEY_FIELD_TYPE_LABEL = "label";
export declare const KEY_FIELD_TYPE_CHECKBOX_LIST = "checkbox_list";
export declare const KEY_FIELD_TYPE_COMBOBOX = "combobox";
export declare const KEY_FIELD_VALUES_LIST = "values_list";
export declare const KEY_FIELD_TYPE_IMAGE = "image";
export declare const KEY_FIELD_VALUE = "value";
export declare const KEY_FIELD_ERROR = "error";
export declare const KEY_FIELD_MAX_LENGTH = "max_length";
export declare const KEY_FIELD_AUTO_FOCUS = "auto_focus";
export declare const KEY_FIELD_INDEX_CONTENT = "index_content";
export declare const KEY_FIELD_AUTO_RENDER = "auto_render";
export declare const KEY_FIELD_COMPARE = "key_field_compare";
export declare const KEY_FIELD_LINK = "field_link";
export declare const KEY_FIELD_LIST_CRON_TRIGGER = "list_cron_trigger";
export declare const KEY_FIELD_VIEW_CRON_VALUE = "view_cron_value";
export declare const KEY_FIELD_RULES = "rules";
export declare const KEY_FIELD_RULE_EMPTY = "rules_empty";
export declare const KEY_FIELD_RULE_NUMBER = "rules_number";
export declare const KEY_FIELD_RULE_PHONE_NUMBER = "rules_phone_number";
export declare const KEY_FIELD_RULE_EMAIL = "rules_email";
export declare const KEY_FIELD_RULE_COMPARE = "rules_compare";
export declare const KEY_FIELD_RULE_CHARACTERS = "rules_characters";
export declare const KEY_FIELD_RULE_CHARACTERS_UTF8 = "rules_characters_utf8";
export declare const KEY_FIELD_RULE_18_PLUS = "rules_18_plus";
export declare const KEY_FIELD_RULE_PASSWORD = "rules_password";
export declare const KEY_FIELD_RULE_SIZE_LENGTH = "rules_size_length";
export declare const KEY_FIELD_RULE_IMAGE = "rules_image";
