export const IO_CONFIGURATION_TYPE = {
    FETCHING_COUNT: 'IO_CONFIGURATION_FETCHING_COUNT',
    RECEIVE_COUNT: 'IO_CONFIGURATION_RECEIVE_COUNT',
    DID_INVALIDATE_COUNT: 'IO_CONFIGURATION_DID_INVALIDATE_COUNT',
    RESET: 'IO_CONFIGURATION_RESET',
    ADD_EXPORT: 'IO_CONFIGURATION_ADD_EXPORT',
    REMOVE_EXPORT: 'IO_CONFIGURATION_REMOVE_EXPORT',
    FETCHING_EXPORT: 'IO_CONFIGURATION_FETCHING_EXPORT',
    RECEIVE_EXPORT: 'IO_CONFIGURATION_RECEIVE_EXPORT',
    DID_INVALIDATE_EXPORT: 'IO_CONFIGURATION_DID_INVALIDATE_EXPORT',
    DOWNLOADED_EXPORT: 'IO_CONFIGURATION_DOWNLOADED_EXPORT',
}

export const IO_CONFIGURATION_PROJECTS_TYPE = {
    FETCHING: 'IO_CONFIGURATION_PROJECTS_FETCHING',
    RECEIVE: 'IO_CONFIGURATION_PROJECTS_RECEIVE',
    DID_INVALIDATE: 'IO_CONFIGURATION_PROJECTS_DID_INVALIDATE',
    SELECT_PROJECT: 'IO_CONFIGURATION_SELECT_PROJECT',
    RESET: 'IO_CONFIGURATION_PROJECTS_RESET',
}

export const IO_CONFIGURATION_IMPORT = {
    SET_SOURCE_FROM: 'IO_CONFIGURATION_IMPORT_SET_SOURCE_FROM',
    SET_DATA_FROM_FILE: 'IO_CONFIGURATION_SET_DATA_FROM_FILE',
    RESET: 'IO_CONFIGURATION_PROJECTS_RESET',
    IMPORTING:'IO_CONFIGURATION_PROJECTS_IMPORTING',
    IMPORT_SUCCESS:'IO_CONFIGURATION_PROJECTS_IMPORT_SUCCESS',
    FETCHING_COUNT: 'IO_CONFIGURATION_FETCHING_COUNT_IMPORT',
    RECEIVE_COUNT: 'IO_CONFIGURATION_RECEIVE_COUNT_IMPORT',
    DID_INVALIDATE_COUNT: 'IO_CONFIGURATION_DID_INVALIDATE_COUNT_IMPORT',
    ADD_IMPORT: 'IO_CONFIGURATION_ADD_IMPORT',
    REMOVE_IMPORT: 'IO_CONFIGURATION_REMOVE_IMPORT',

}
