export const BREADCRUMB_PROJECT_INDEX = 0;
export const BREADCRUMB_MODULE_INDEX = 1;
export const BREADCRUMB_DEFAULT_LENGTH = 2;

export const PATHNAME_DEFAULT_LENGTH = 5;
export const PATHNAME_PROJECT_ID_INDEX = 2;
export const PATHNAME_MODULE_INDEX = 3;

export const PROJECT_BREADCRUMB_RESET = 'PROJECT_BREADCRUMB_RESET';

export const PROJECT_BREADCRUMB_CREATE = 'PROJECT_BREADCRUMB_CREATE';
export const PROJECT_BREADCRUMB_SHOW_SUB = 'PROJECT_BREADCRUMB_SHOW_SUB';
export const PROJECT_BREADCRUMB_HIDE_SUB = 'PROJECT_BREADCRUMB_HIDE_SUB';
export const PROJECT_BREADCRUMB_SEND_EXTEND = 'PROJECT_BREADCRUMB_SEND_EXTEND';
export const PROJECT_BREADCRUMB_RECEIVE_EXTEND =
  'PROJECT_BREADCRUMB_RECEIVE_EXTEND';

export const PROJECT_API_LINK = ` http://sit.api.x.digi-texx.vn/projects`;

export const PROJECT_GET_LIST = 'PROJECT_GET_LIST';

export const PROJECT_GET_BY_ID = 'PROJECT_GET_BY_ID';

export const PROJECT_OPEN_MODIFY = 'PROJECT_OPEN_MODIFY';

export const PROJECT_CLOSE_MODIFY = 'PROJECT_CLOSE_MODIFY';

export const PROJECT_INSERT = 'PROJECT_INSERT';

export const PROJECT_UPDATE = 'PROJECT_UPDATE';

export const CANCEL_ACTION_MODIFY = 'CANCEL_ACTION_MODIFY';

/**
 * AJAX ACTION DEFINITION
 */

export const PROJECT_SEND_HTTP_REQUEST = 'PROJECT_SEND_HTTP_REQUEST';
export const PROJECT_RECEIVE_HTTP_RESPONSE = 'PROJECT_RECEIVE_HTTP_RESPONSE';
export const PROJECT_RESPOND_OPEN_SNACKBAR = 'PROJECT_RESPOND_OPEN_SNACKBAR';
export const PROJECT_REQUEST_OPEN_SNACKBAR = 'PROJECT_REQUEST_OPEN_SNACKBAR';
export const PROJECT_CLOSE_SNACKBAR = 'PROJECT_CLOSE_SNACKBAR';

/**
 * AJAX ACTION DEFINITION
 */

export const PROJECT_ITEM_SET_DIALOG = 'PROJECT_ITEM_SET_DIALOG';

/**
 * PARAMETER ITEM
 */
export const KEY_PROJECT_NAME = 'name';
export const KEY_PROJECT_PRIORITY = 'priority';
export const KEY_PROJECT_CUSTOMER = 'customer';
export const KEY_PROJECT_ACTIVE = 'active';
export const KEY_PROJECT_ID = 'id';
export const KEY_PROJECT_GROUP_ID = 'group_id';
export const KEY_PROJECT_FOLDER = 'folder';

/**
 * PROJECT LIST
 */
export const PROJECT_LIST_REQUEST = 'PROJECT_LIST_REQUEST';
export const PROJECT_LIST_RESET_DATA = 'PROJECT_LIST_RESET_DATA';
export const PROJECT_LIST_RECEIVE_DATAS = 'PROJECT_LIST_RECEIVE_DATAS';
export const PROJECT_LIST_PUSH_DATA_INTO_LIST = 'PROJECT_LIST_PUSH_DATA_INTO_LIST';
export const PROJECT_LIST_REMOVE_DATA_FROM_LIST = 'PROJECT_LIST_REMOVE_DATA_FROM_LIST';

/**
 * PROJECT ITEM ACTION
 */
export const PROJECT_ITEM_REQUEST_DATA = 'PROJECT_ITEM_REQUEST_DATA';
export const PROJECT_ITEM_RECEIVE_DATA = 'PROJECT_ITEM_RECEIVE_DATA';
export const PROJECT_ITEM_INSERT_DATA = 'PROJECT_ITEM_INSERT_DATA';
export const PROJECT_ITEM_UPDATE_DATA = 'PROJECT_ITEM_UPDATE_DATA';
export const PROJECT_ITEM_MODIFY_DATA = 'PROJECT_ITEM_MODIFY_DATA';
export const PROJECT_ITEM_RESET_DATA = 'PROJECT_ITEM_RESET_DATA';
export const PROJECT_ITEM_START_MODIFY_DATA = 'PROJECT_ITEM_START_MODIFY_DATA';
export const PROJECT_ITEM_STOP_MODIFY_DATA = 'PROJECT_ITEM_STOP_MODIFY_DATA';

export const PROJECT_GROUP_REQUEST = 'PROJECT_GROUP_REQUEST';
export const PROJECT_GROUP_RECEIVE = 'PROJECT_GROUP_RECEIVE';
export const PROJECT_GROUP_SELECTED = 'PROJECT_GROUP_SELECTED';
export const PROJECT_GROUP_RESET_STATE = 'PROJECT_GROUP_RESET_STATE';
