export const SELECT_PROJECT_LIST_REQUEST = 'SELECT_PROJECT_LIST_REQUEST';
export const SELECT_PROJECT_RESET_STATE = 'SELECT_PROJECT_RESET_STATE';
export const SELECT_PROJECT_LIST_RECEIVE_DATAS = 'SELECT_PROJECT_LIST_RECEIVE_DATAS';
export const SELECT_PROJECT_SELECT_ITEM = 'SELECT_PROJECT_SELECT_ITEM';