/**
 * COMMON
 */
export const GROUP_MANAGEMENT_DONE_GET_PARAMS =
  'GROUP_MANAGEMENT_DONE_GET_PARAMS';
export const GROUP_MANAGEMENT_NOT_FOUND = 'GROUP_MANAGEMENT_NOT_FOUND';
export const GROUP_MANAGEMENT_HIDE_DIALOG = 'GROUP_MANAGEMENT_HIDE_DIALOG';
export const GROUP_MANAGEMENT_SHOW_DIALOG = 'GROUP_MANAGEMENT_SHOW_DIALOG';
export const GROUP_MANAGEMENT_TOGGLE_DETAIL = 'GROUP_MANAGEMENT_TOGGLE_DETAIL';
export const GROUP_MANAGEMENT_TOGGLE_GROUP_TREE =
  'GROUP_MANAGEMENT_TOGGLE_GROUP_TREE';
export const GROUP_MANAGEMENT_REDIRECT_GROUP =
  'GROUP_MANAGEMENT_REDIRECT_GROUP';

/**
 * TREE GROUPS
 */
export const GROUP_TREE_REQUEST = 'GROUP_TREE_REQUEST';
export const GROUP_TREE_RESET_DATA = 'GROUP_TREE_RESET_DATA';
export const GROUP_TREE_RESPONSE = 'GROUP_TREE_RESPONSE';

/**
 * GROUP ITEM
 */

export const GROUP_ITEM_RESET_DATA = 'GROUP_ITEM_RESET_DATA';
export const GROUP_ITEM_REQUEST = 'GROUP_ITEM_REQUEST';
export const GROUP_ITEM_RESPONSE = 'GROUP_ITEM_RESPONSE';
export const GROUP_ITEM_SELECT_GROUP = 'GROUP_ITEM_SELECT_GROUP';
export const GROUP_ITEM_UPDATE_DETAILS = 'GROUP_ITEM_UPDATE_DETAILS';
export const GROUP_ITEM_UPDATE_BREADCRUMB = 'GROUP_ITEM_UPDATE_BREADCRUMB';
export const GROUP_ITEM_ACTION_TYPE_UPDATE = 'GROUP_ITEM_ACTION_TYPE_UPDATE';
export const GROUP_ITEM_ACTION_TYPE_CREATE = 'GROUP_ITEM_ACTION_TYPE_CREATE';
export const GROUP_ITEM_ACTION_TYPE_DELETE = 'GROUP_ITEM_ACTION_TYPE_DELETE';
export const GROUP_ITEM_UPDATE_STATISTIC = 'GROUP_ITEM_UPDATE_STATISTIC';

/**
 * PROJECT ITEM
 */

export const PROJECT_INFO_UPDATE_INFOS = 'PROJECT_INFO_UPDATE_INFOS';
export const PROJECT_ITEM_UPDATE_NAME = 'PROJECT_ITEM_UPDATE_NAME';
/**
 *
 */

export const GROUP_ACTION_UN_SELECTED = -1;
export const GROUP_MANAGEMENT_TYPE_GROUP = 'Group';
export const GROUP_MANAGEMENT_TYPE_PROJECT = 'Project';
/**
 *
 */
export const GROUP_MANAGEMENT_INDEX_GROUP_ID = 2;

/**
 * SORT KEY
 */
export const GROUP_MANAGEMENT_CHANGE_ORDER_SETTING =
  'GROUP_MANAGEMENT_CHANGE_ORDER_SETTING';

export const GROUP_MANAGEMENT_ORDER_KEY_NAME = 'name';
export const GROUP_MANAGEMENT_ORDER_KEY_PRIORITY = 'priority';
export const GROUP_MANAGEMENT_ORDER_KEY_CREATED_DATE = 'created_date';
export const GROUP_MANAGEMENT_ORDER_KEY_TOTAL_TASK = 'total_task';

export const GROUP_MANAGEMENT_ORDER_BY_ASC = 'asc';
export const GROUP_MANAGEMENT_ORDER_BY_DESC = 'desc';

/**
 * GROUP statistic detail
 */
export const GROUP_STATISTIC_TOTAL_GROUPS = 'total_group';
export const GROUP_STATISTIC_TOTAL_PROJECT = 'total_project';
export const GROUP_STATISTIC_TOTAL_TASKS = 'total_task';
export const GROUP_STATISTIC_TOTAL_WORKING_USER = 'total_working_user';
